server:
  port: 80

spring:
  application:
    name: @project.artifactId@
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

enba:
  #  公众号
  mp:
    app-id: 自己公众号的appid
    app-secret: 自己公众号的appsecret
    redirect-uri: 微信授权登录成功之后的回调地址
  #  微信Jsapi支付
  jsapi:
    merchant-id: 商户号
    privateKey-path: 商户私钥路径
    merchant-serial-number: 商户API证书序列号
    api-v3-key: APIv3密钥
    notify-url: 支付回调地址